#!/usr/bin/env python3
"""Project agents CLI — compose root AGENTS.md as a routing index.

Seeded/refreshed by the shellrc `agents` tool. Full guidelines stay under
agents/installed/; this script builds a when-to-read map only.

Commands: build | help | --version
"""

from __future__ import annotations

import argparse
import os
import re
import sys
import tempfile
from pathlib import Path
from typing import List, Optional, Sequence, Set, Tuple

PROJECT_ROOT = Path(__file__).resolve().parent
AGENTS_DIR = PROJECT_ROOT / "agents"
INSTALLED_DIR = AGENTS_DIR / "installed"
ALWAYS_FILENAME = "always.md"

__version__ = "0.6.1"
# agents-tool-version: 0.6.1

CORE_INSTALLED_RELS = (
    "always.md",
    "general.md",
    "security.md",
    "git.md",
    "scripting.md",
    "comments.md",
    "documentation.md",
    "testing.md",
    "ansi-colors.md",
    "markdown.md",
)
FULL_EXTRAS = ("nvim.md", "secrets.md")
VOLATILE_PREFIXES = ("plans/", "tasks/", "ideas/")
PRESETS = ("core", "full", "all")

HEADER = (
    "<!-- Generated by agents.py — do not edit by hand.\n"
    "     Routing index only: full rules live under agents/ and agents/installed/.\n"
    "     Open linked files when their trigger matches; do not invent rules.\n"
    "     Do not gitignore this file: Grok skips gitignored project instructions. -->\n"
    "\n"
)

_KERNEL_MISSING_STUB = (
    "## Hard kernel (always on)\n"
    "\n"
    "> **Kernel missing** — `agents/installed/always.md` not found. "
    "Run `agents install always` (or `agents init` / `agents update --all` "
    "once the catalog ships `always`).\n"
)

_FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n?", re.DOTALL)

HANDBOOK_SESSION_FILES = (
    ("user.md", "Who the human is and how to work together. Not product law"),
    ("README.md", "How this handbook is run"),
    ("project.md", "What this project is"),
    ("architecture.md", "How it is built and how it runs"),
    (
        "host-constraints.md",
        "Host limits (when present). Human-owned; do not add an id without named permission",
    ),
    ("glossary.md", "Words"),
    (
        "conflicts.md",
        "Active rule conflicts, then leftovers. Retired decisions are `conflicts-resolved.md` and are not rules",
    ),
    ("acceptance.md", "When work is complete"),
    ("priority.md", "What to do next"),
)


def is_volatile(rel: str) -> bool:
    norm = rel.replace("\\", "/")
    return any(norm == p.rstrip("/") or norm.startswith(p) for p in VOLATILE_PREFIXES)


def _rel_posix(base: Path, path: Path) -> str:
    return str(path.relative_to(base)).replace(os.sep, "/")


def bump_headings(text: str) -> str:
    result: List[str] = []
    in_code = False
    fence = ""
    for line in text.splitlines(keepends=False):
        stripped = line.lstrip()
        if stripped.startswith(("```", "~~~")):
            if not in_code:
                in_code = True
                fence = stripped[:3]
            elif stripped.startswith(fence):
                in_code = False
            result.append(line)
            continue
        if not in_code:
            m = re.match(r"^(\s*)(#{1,6})(.*)$", line)
            if m:
                indent, hashes, rest = m.groups()
                if len(hashes) < 6:
                    result.append(indent + "#" + hashes + rest)
                    continue
        result.append(line)
    return "\n".join(result) + ("\n" if text.endswith("\n") else "")


def strip_frontmatter(text: str) -> str:
    m = _FRONTMATTER_RE.match(text)
    return text[m.end() :] if m else text


def load_hard_kernel() -> str:
    path = INSTALLED_DIR / ALWAYS_FILENAME
    if not path.is_file():
        return _KERNEL_MISSING_STUB
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError:
        return _KERNEL_MISSING_STUB
    body = strip_frontmatter(raw).strip("\n")
    if not body.strip():
        return _KERNEL_MISSING_STUB
    first = next((ln for ln in body.splitlines() if ln.strip()), "")
    if first.lstrip().startswith("#"):
        return bump_headings(body).rstrip() + "\n"
    return "## Hard kernel (always on)\n\n" + body.rstrip() + "\n"


def _ownership_table() -> List[str]:
    rows = [
        "| Path | Edit how |",
        "| --- | --- |",
        "| `AGENTS.md` (this file) | **Never** by hand — only `agents build` |",
        "| `README.md` (product) | **Human** — agents read; write only with explicit permission |",
        "| `agents/README.md`, `project.md`, `architecture.md`, `acceptance.md` | **Human** — propose edits; apply only with permission |",
        "| `agents/general.md`, `documentation.md`, `testing.md` (when present) | **Human** — propose edits; apply only with permission |",
    ]
    if (AGENTS_DIR / "host-constraints.md").is_file():
        rows.append(
            "| `agents/host-constraints.md` | **Human, stricter** — current message "
            "must name this file; exhaustive proposal to add or widen an id. "
            "Architecture permission is not enough |"
        )
    rows.extend(
        [
            "| `agents/user.md` | **Human** — who the human is and how to collaborate. Not product law |",
            "| `agents/glossary.md` | **Agent** — words |",
            "| `agents/priority.md` | **Agent** — ordered list of plans |",
            "| `agents/conflicts.md` | **Agent** — active rule conflicts, and leftovers that lag a settled rule |",
            "| `agents/conflicts-resolved.md` | **Agent** — append a retired row only. "
            "Rows are **not rules** (decisions at a moment, while architecture "
            "and the rest of the handbook were taking shape). Do not delete "
            "this file or the section that says the rows are not rules. "
            "Removing that section does not make the rows into rules. "
            "Order: `agents/general.md` Conflicts, or catalog `general.md` "
            "Conflicts when the project has no handbook copy |",
            "| `agents/plans/` | **Shared** — one plan per piece of work |",
            "| `agents/ideas/` | Parked ideas |",
            "| `agents/installed/*` | **Only** `agents install` / `agents update` — never hand-edit |",
            "| `agents/<same-as-installed>` | **Extension** (default) — amends installed; wins on conflict |",
            "| `agents/<stem>.extend.md` | Explicit extension (same rules; do not mix with same-name) |",
            "| `agents/<stem>.override.md` | **Override** — replaces installed for that id (rare fork) |",
        ]
    )
    return rows


def _session_start_table() -> List[str]:
    rows = [
        "| Path | Read when |",
        "| --- | --- |",
    ]
    for name, when in HANDBOOK_SESSION_FILES:
        if (AGENTS_DIR / name).is_file():
            rows.append(f"| `agents/{name}` | {when} |")
    rows.append(
        "| The active plan named in `agents/priority.md` | Goal, acceptance, session |"
    )
    return rows


def _parse_route(text: str) -> Tuple[str, str, int]:
    m = _FRONTMATTER_RE.match(text)
    title, read_when, order = "", "", 100
    if not m:
        return title, read_when, order
    for raw in m.group(1).splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip().lower()
        val = val.strip().strip('"').strip("'")
        if key == "title":
            title = val
        elif key in ("read_when", "when"):
            read_when = val
        elif key == "order":
            try:
                order = int(val)
            except ValueError:
                pass
    return title, read_when, order


def route_from_path(path: Path) -> Tuple[str, str, int]:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return path.stem.replace("-", " ").title(), "When relevant", 100
    title, read_when, order = _parse_route(text)
    if not title:
        title = path.stem.replace("-", " ").title()
    if not read_when:
        read_when = "When relevant to the task — open this file (add read_when frontmatter)"
    return title, read_when, order


def _label_for(path: Path) -> str:
    return _rel_posix(AGENTS_DIR, path)


def _user_layer_label(rel: str, kind: str) -> str:
    if kind == "override":
        return f"{rel} (override)"
    return f"{rel} (extension)"


def _layer_candidates(rel: str):
    stem = rel[:-3] if rel.endswith(".md") else rel
    return {
        "extend": AGENTS_DIR / rel,
        "extend_explicit": AGENTS_DIR / f"{stem}.extend.md",
        "override": AGENTS_DIR / f"{stem}.override.md",
    }


def _discover_user_layer(rel: str):
    cands = _layer_candidates(rel)
    found = []
    if cands["extend"].is_file():
        found.append(("extend", cands["extend"]))
    if cands["extend_explicit"].is_file():
        found.append(("extend", cands["extend_explicit"]))
    if cands["override"].is_file():
        found.append(("override", cands["override"]))
    if not found or len(found) > 1:
        return None
    return found[0]


def _is_user_layer_path(path: Path, installed_rels) -> bool:
    try:
        resolved = path.resolve()
    except OSError:
        return False
    for irel in installed_rels:
        for cand in _layer_candidates(irel).values():
            try:
                if cand.resolve() == resolved:
                    return True
            except OSError:
                continue
    return False


def _resolve_under_agents(arg: str) -> Optional[Path]:
    clean = arg.replace("\\", "/")
    for prefix in ("agents/", "./agents/"):
        if clean.startswith(prefix):
            clean = clean[len(prefix):]
            break
    cand = (AGENTS_DIR / clean).resolve()
    try:
        if cand.is_relative_to(AGENTS_DIR.resolve()) and cand.exists():
            return cand
    except (ValueError, OSError):
        pass
    if not clean.startswith("installed/"):
        cand2 = (INSTALLED_DIR / clean).resolve()
        try:
            if cand2.is_relative_to(AGENTS_DIR.resolve()) and cand2.exists():
                return cand2
        except (ValueError, OSError):
            pass
    return None


def collect_fragments(
    preset: str = "core",
    paths: Sequence[str] = (),
    *,
    include_readme: bool = False,
) -> List[Tuple[str, Path]]:
    result: List[Tuple[str, Path]] = []
    seen: Set[str] = set()
    has_installed = INSTALLED_DIR.is_dir() and any(INSTALLED_DIR.rglob("*.md"))
    installed_rels: Set[str] = set()

    def add_labeled(label: str, path: Path) -> None:
        if label not in seen and path.is_file():
            result.append((label, path))
            seen.add(label)

    def existing_managed(rel: str) -> Optional[Path]:
        p = INSTALLED_DIR / rel
        if p.is_file():
            installed_rels.add(rel)
            return p
        if has_installed:
            return None
        p2 = AGENTS_DIR / rel
        if p2.is_file() and rel != "project.md":
            return p2
        return None

    if include_readme or preset == "all":
        readme = PROJECT_ROOT / "README.md"
        if readme.is_file():
            add_labeled("../README.md", readme)

    project_md = AGENTS_DIR / "project.md"
    if project_md.is_file():
        add_labeled("project.md", project_md)

    for rel in CORE_INSTALLED_RELS:
        p = existing_managed(rel)
        if p is not None:
            add_labeled(_label_for(p.resolve()), p)

    extras: List[Path] = []
    # Index mode: core/full list ALL installed guidelines (so install appears in index)
    if preset in ("core", "full") and INSTALLED_DIR.is_dir():
        for md in sorted(INSTALLED_DIR.rglob("*.md")):
            rel = _rel_posix(INSTALLED_DIR, md)
            installed_rels.add(rel)
            if is_volatile(rel):
                continue
            if rel in CORE_INSTALLED_RELS:
                continue
            extras.append(md)
        for md in sorted(AGENTS_DIR.glob("*.md")):
            if md.name.startswith("."):
                continue
            extras.append(md)
    elif preset == "all":
        if AGENTS_DIR.is_dir():
            for md in sorted(AGENTS_DIR.rglob("*.md")):
                if not md.name.startswith("."):
                    extras.append(md)

    for arg in paths:
        target = _resolve_under_agents(arg)
        if target is None:
            print(f"warning: path not found under agents/: {arg}", file=sys.stderr)
            continue
        if target.is_file():
            extras.append(target)
        elif target.is_dir():
            for md in sorted(target.rglob("*.md")):
                if not md.name.startswith("."):
                    extras.append(md)

    stable: List[Tuple[str, Path]] = []
    volatile: List[Tuple[str, Path]] = []
    for p in extras:
        try:
            p = p.resolve()
            if not p.is_file():
                continue
            if p.parent == PROJECT_ROOT and p.name == "README.md":
                label = "../README.md"
            else:
                if not p.is_relative_to(AGENTS_DIR.resolve()):
                    continue
                rel_agents = _rel_posix(AGENTS_DIR, p)
                if (
                    has_installed
                    and not rel_agents.startswith("installed/")
                    and not is_volatile(rel_agents)
                    and rel_agents != "project.md"
                    and (
                        (INSTALLED_DIR / rel_agents).is_file()
                        or _is_user_layer_path(p, installed_rels)
                    )
                ):
                    if (INSTALLED_DIR / rel_agents).is_file():
                        installed_rels.add(rel_agents)
                    continue
                label = _label_for(p)
        except (ValueError, OSError):
            continue
        if label in seen:
            continue
        if is_volatile(label) or (
            label.startswith("installed/")
            and is_volatile(label[len("installed/"):])
        ):
            volatile.append((label, p))
        else:
            stable.append((label, p))

    for label, p in sorted(stable, key=lambda t: t[0]):
        add_labeled(label, p)

    if has_installed and INSTALLED_DIR.is_dir():
        for md in INSTALLED_DIR.rglob("*.md"):
            installed_rels.add(_rel_posix(INSTALLED_DIR, md))
        if preset in ("core", "full", "all"):
            for rel in sorted(installed_rels):
                if is_volatile(rel):
                    continue
                layer = _discover_user_layer(rel)
                if layer is None:
                    continue
                kind, user_p = layer
                add_labeled(_user_layer_label(rel, kind), user_p)

    for label, p in sorted(volatile, key=lambda t: t[0]):
        add_labeled(label, p)
    return result


def compose_index(fragments: Sequence[Tuple[str, Path]]) -> str:
    kernel = load_hard_kernel()
    always_path = INSTALLED_DIR / ALWAYS_FILENAME
    kernel_note = (
        "Hard kernel below is inlined from `agents/installed/always.md` "
        "(catalog `always`); full security/git rules live under "
        "`agents/installed/` — open them when the domain matches."
        if always_path.is_file()
        else "Hard kernel file missing — install catalog `always` "
        "(`agents install always`)."
    )
    parts: List[str] = [
        HEADER.rstrip("\n"),
        "",
        "# Agent routing index",
        "",
        "This file is a **map**, not the full rulebook. It is **transpiled** by "
        "`agents build` from the `agents/` handbook (session start) + "
        "`agents/installed/` (catalog guidelines) + optional user **extensions** / rare **overrides**. "
        "**When a row's trigger matches, open that path and follow it** before acting.",
        "",
        "## Ownership",
        "",
        *_ownership_table(),
        "",
        kernel_note,
        "",
        kernel.rstrip("\n"),
        "",
        "## Session start",
        "",
        "Read these when beginning or resuming work on this project:",
        "",
        *_session_start_table(),
        "",
        "## Queue paths (not auto-loaded)",
        "",
        "| Path | Role |",
        "| --- | --- |",
        "| `agents/priority.md` | Ordered list of plans |",
        "| `agents/plans/` | Active plans |",
        "| `agents/plans/archived/` | Finished or dropped plans |",
        "| `agents/ideas/` | Parked ideas |",
        "| `agents/conflicts-resolved.md` | Retired conflict decisions. "
        "Not rules. Not a session-start read. Do not delete the file or "
        "the section that says the rows are not rules |",
        "",
        "Load plan files **on demand** for the current work only. "
        "The target architecture is `agents/architecture.md`. "
        "Human waits live on the plan, labeled in `agents/priority.md`. "
        "`agents/conflicts-resolved.md` is a trail of old decisions. "
        "It is not architecture. Open it only to see whether a leftover "
        "was already retired.",
        "",
        "## Guidelines (open when trigger matches)",
        "",
        "| Path | Title | Read when |",
        "| --- | --- | --- |",
    ]
    rows: List[Tuple[int, str, str, str]] = []
    for label, path in fragments:
        if label == "project.md":
            continue
        try:
            rel = path.resolve().relative_to(AGENTS_DIR.resolve())
            rel_read = "agents/" + str(rel).replace(os.sep, "/")
        except ValueError:
            rel_read = label
        norm = rel_read.replace("\\", "/")
        if "/plans/" in norm or norm.startswith("agents/plans/"):
            continue
        if "/tasks/" in norm or norm.startswith("agents/tasks/"):
            continue
        if "/ideas/" in norm or norm.startswith("agents/ideas/"):
            continue
        if path.name == ALWAYS_FILENAME or norm.endswith(f"/{ALWAYS_FILENAME}"):
            continue
        title, read_when, order = route_from_path(path)
        # Full override replaces installed row for that id
        if label.startswith("installed/"):
            irel = label[len("installed/") :]
            layer = _discover_user_layer(irel)
            if layer and layer[0] == "override":
                continue
        if label.endswith(" (extension)"):
            try:
                rel_read = "agents/" + str(path.resolve().relative_to(AGENTS_DIR.resolve())).replace(os.sep, "/")
            except ValueError:
                rel_read = "agents/" + label[: -len(" (extension)")]
            title = f"{title} (extension)"
        elif label.endswith(" (override)"):
            try:
                rel_read = "agents/" + str(path.resolve().relative_to(AGENTS_DIR.resolve())).replace(os.sep, "/")
            except ValueError:
                rel_read = "agents/" + label[: -len(" (override)")]
            title = f"{title} (override)"
        rows.append((order, rel_read, title, read_when))
    rows.sort(key=lambda r: (r[0], r[1]))
    for _o, rel_read, title, read_when in rows:
        te = title.replace("|", "\\|")
        we = read_when.replace("|", "\\|")
        parts.append(f"| `{rel_read}` | {te} | {we} |")
    if not rows:
        parts.append("| *(none installed)* | — | Run `agents init` / `agents install` |")
    parts.extend(
        [
            "",
            "## How to use this index",
            "",
            "1. Match your action to **Read when**.",
            "2. **Open the Path** (Read tool / editor) and follow that file.",
            "3. Prefer catalog → `agents update` for portable rules. "
            "**Extensions** (`agents/<same-as-installed>` or `*.extend.md`) amend "
            "the matching `agents/installed/…` file and **take precedence on "
            "conflict**. **Overrides** (`*.override.md`) replace installed for "
            "that id — rare; prefer extension or a catalog fix. Do not mix the "
            "three forms for one id (`agents update` errors if you do).",
            "4. Do not paste entire guideline files into chat; follow them in place.",
            "5. Rebuild after install/update: `agents build` or `python3 agents.py build`.",
            "6. Full ownership and working rules: `agents/general.md` "
            "(or catalog `general.md` if this project has no handbook copy). "
            "On conflict with `agents/installed/`, the handbook files win.",
            "",
        ]
    )
    return "\n".join(parts).rstrip() + "\n"


def write_atomic(target: Path, content: str) -> bool:
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.is_file():
        try:
            if target.read_text(encoding="utf-8") == content:
                return False
        except OSError:
            pass
    fd, tmp_name = tempfile.mkstemp(
        prefix=".AGENTS.", suffix=".tmp", dir=str(target.parent)
    )
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp_path, target)
    except Exception:
        try:
            tmp_path.unlink(missing_ok=True)
        except OSError:
            pass
        raise
    return True


def cmd_build(argv: Sequence[str]) -> int:
    parser = argparse.ArgumentParser(
        prog="agents.py build",
        description="Compose AGENTS.md routing index from agents/ + installed guidelines.",
    )
    parser.add_argument("paths", nargs="*", help="Extra paths under agents/ to index")
    parser.add_argument("--preset", choices=PRESETS, default="core")
    parser.add_argument("--readme", action="store_true")
    parser.add_argument("-o", "--output")
    parser.add_argument("--stdout", action="store_true")
    parser.add_argument("--list", action="store_true")
    args = parser.parse_args(list(argv))

    if not AGENTS_DIR.is_dir():
        print(f"error: agents/ not found under {PROJECT_ROOT}", file=sys.stderr)
        return 2

    frags = collect_fragments(args.preset, args.paths, include_readme=args.readme)
    if args.list:
        for label, _ in frags:
            print(label)
        return 0

    content = compose_index(frags)
    if args.stdout:
        sys.stdout.write(content)
        return 0

    if args.output:
        target = Path(args.output)
        if not target.is_absolute():
            target = (Path.cwd() / target).resolve()
        if target.is_dir() or str(args.output).endswith(("/", "\\")):
            target = target / "AGENTS.md"
    else:
        target = PROJECT_ROOT / "AGENTS.md"

    try:
        changed = write_atomic(target, content)
    except OSError as exc:
        print(f"error: write failed: {exc}", file=sys.stderr)
        return 1
    try:
        disp = str(target.relative_to(Path.cwd().resolve()))
    except ValueError:
        disp = str(target)
    print(f"Wrote {disp}" if changed else f"Unchanged {disp} (cache-stable)")
    return 0


def usage() -> None:
    print(
        f"""agents.py {__version__} — project agents routing-index composer

Commands:
  build [paths…]     Compose root AGENTS.md index (default --preset=core)
  help               This help
  --version          Print version

AGENTS.md is a **when-to-read map**. Full rules stay in agents/installed/.
Hard kernel is inlined from agents/installed/always.md.
Install/update fragments with the shellrc `agents` tool.
"""
    )


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if not args or args[0] in ("-h", "--help", "help"):
        usage()
        return 0
    if args[0] in ("--version", "-V", "version"):
        print(f"agents.py {__version__}")
        return 0
    if args[0] == "build":
        return cmd_build(args[1:])
    print(
        f"error: unknown command {args[0]!r} (try: build, help, --version)",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
